export type FileFilter = { name: string; extensions: string[] }

/** 拡張子 → Monaco 言語 ID。開くこと自体は「すべてのファイル」で常に可能。 */
export const LANGUAGE_BY_EXT: Record<string, string> = {
  txt: 'plaintext',
  text: 'plaintext',
  log: 'plaintext',
  out: 'plaintext',
  err: 'plaintext',
  nfo: 'plaintext',
  diz: 'plaintext',
  lst: 'plaintext',
  csv: 'plaintext',
  tsv: 'plaintext',
  tab: 'plaintext',
  diff: 'plaintext',
  patch: 'plaintext',
  srt: 'plaintext',
  vtt: 'plaintext',
  ass: 'plaintext',
  ssa: 'plaintext',
  ics: 'plaintext',
  vcf: 'plaintext',
  po: 'plaintext',
  pot: 'plaintext',
  m3u: 'plaintext',
  m3u8: 'plaintext',

  md: 'markdown',
  markdown: 'markdown',
  mdx: 'markdown',
  rmd: 'markdown',
  qmd: 'markdown',
  rst: 'restructuredtext',
  rest: 'restructuredtext',

  bat: 'bat',
  cmd: 'bat',
  vb: 'vb',
  vbs: 'vb',
  vbe: 'vb',
  vba: 'vb',
  bas: 'vb',
  frm: 'vb',
  cls: 'vb',
  ctl: 'vb',
  dsr: 'vb',
  vbhtml: 'razor',
  ps1: 'powershell',
  psm1: 'powershell',
  psd1: 'powershell',
  pssc: 'powershell',
  psrc: 'powershell',
  msh: 'powershell',
  msh1: 'powershell',
  msh2: 'powershell',
  psc1: 'xml',
  ps1xml: 'xml',
  cdxml: 'xml',
  reg: 'ini',
  inf: 'ini',
  url: 'ini',
  website: 'ini',
  ins: 'ini',
  isp: 'ini',
  cfg: 'ini',
  config: 'xml',
  wsf: 'xml',
  wsh: 'ini',
  wsc: 'xml',
  sct: 'xml',
  ws: 'vb',
  hta: 'html',
  htc: 'html',
  nsi: 'plaintext',
  nsh: 'plaintext',
  iss: 'pascal',
  ahk: 'plaintext',
  au3: 'plaintext',
  sln: 'plaintext',
  csproj: 'xml',
  vbproj: 'xml',
  fsproj: 'xml',
  vcxproj: 'xml',
  vcproj: 'xml',
  proj: 'xml',
  props: 'xml',
  targets: 'xml',
  filters: 'xml',
  resx: 'xml',
  resw: 'xml',
  xaml: 'xml',
  axaml: 'xml',
  appxmanifest: 'xml',
  nuspec: 'xml',
  wxs: 'xml',
  wxi: 'xml',
  wxl: 'xml',
  rc: 'c',
  idl: 'c',
  def: 'plaintext',

  html: 'html',
  htm: 'html',
  shtml: 'html',
  xhtml: 'html',
  css: 'css',
  scss: 'scss',
  less: 'less',
  sass: 'scss',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  es6: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  cts: 'typescript',
  mts: 'typescript',
  dts: 'typescript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  jsonl: 'json',
  geojson: 'json',
  webmanifest: 'json',
  har: 'json',
  ipynb: 'json',
  map: 'json',
  xml: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  xslt: 'xml',
  wsdl: 'xml',
  svg: 'xml',
  plist: 'xml',
  rss: 'xml',
  atom: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'ini',
  ini: 'ini',
  env: 'ini',
  conf: 'ini',
  editorconfig: 'ini',
  properties: 'ini',
  vue: 'html',
  svelte: 'html',
  astro: 'html',
  hbs: 'handlebars',
  handlebars: 'handlebars',
  ejs: 'html',
  njk: 'html',
  pug: 'pug',
  jade: 'pug',
  twig: 'twig',
  liquid: 'liquid',
  cshtml: 'razor',
  razor: 'razor',
  aspx: 'html',
  ascx: 'html',
  asmx: 'html',
  ashx: 'html',
  master: 'html',
  sitemap: 'xml',

  py: 'python',
  pyw: 'python',
  pyi: 'python',
  go: 'go',
  rs: 'rust',
  java: 'java',
  jav: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  cs: 'csharp',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  'c++': 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  hh: 'cpp',
  ino: 'cpp',
  tpp: 'cpp',
  m: 'objective-c',
  mm: 'objective-c',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  fsscript: 'fsharp',
  pas: 'pascal',
  pp: 'pascal',
  dpr: 'pascal',
  lpr: 'pascal',
  rb: 'ruby',
  rake: 'ruby',
  gemspec: 'ruby',
  php: 'php',
  phtml: 'php',
  php5: 'php',
  pl: 'perl',
  pm: 'perl',
  t: 'perl',
  pod: 'perl',
  lua: 'lua',
  r: 'r',
  dart: 'dart',
  scala: 'scala',
  sc: 'scala',
  groovy: 'java',
  gvy: 'java',
  gradle: 'java',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  ex: 'elixir',
  exs: 'elixir',
  coffee: 'coffeescript',
  litcoffee: 'coffeescript',
  sol: 'solidity',
  tf: 'hcl',
  tfvars: 'hcl',
  hcl: 'hcl',
  nomad: 'hcl',
  bicep: 'bicep',
  proto: 'protobuf',
  graphql: 'graphql',
  gql: 'graphql',
  sql: 'sql',
  mysql: 'mysql',
  pgsql: 'pgsql',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ksh: 'shell',
  cmake: 'makefile',
  mk: 'makefile',
  mak: 'makefile',
  jl: 'julia',
  wgsl: 'wgsl',
  hlsl: 'c',
  glsl: 'c',
  vert: 'c',
  frag: 'c',
  scm: 'scheme',
  ss: 'scheme',
  lisp: 'scheme',
  dockerignore: 'plaintext',
  gitignore: 'plaintext',
  gitattributes: 'plaintext'
}

export const LANGUAGE_BY_FILENAME: Record<string, string> = {
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  'cmakelists.txt': 'makefile',
  jenkinsfile: 'java',
  gemfile: 'ruby',
  rakefile: 'ruby',
  vagrantfile: 'ruby',
  procfile: 'plaintext',
  brewfile: 'ruby',
  podfile: 'ruby',
  fastfile: 'ruby',
  hosts: 'plaintext',
  lmhosts: 'plaintext',
  'hosts.ics': 'plaintext',
  gitignore: 'plaintext',
  gitattributes: 'plaintext',
  gitmodules: 'ini',
  editorconfig: 'ini',
  npmrc: 'ini',
  yarnrc: 'yaml',
  bashrc: 'shell',
  zshrc: 'shell',
  profile: 'shell',
  gitconfig: 'ini'
}

const TEXT_EXTS = [
  'txt',
  'text',
  'md',
  'markdown',
  'mdx',
  'rst',
  'log',
  'csv',
  'tsv',
  'nfo',
  'diff',
  'patch'
]
const WINDOWS_EXTS = [
  'bat',
  'cmd',
  'vb',
  'vbs',
  'vbe',
  'vba',
  'bas',
  'frm',
  'cls',
  'ps1',
  'psm1',
  'psd1',
  'reg',
  'inf',
  'ini',
  'cfg',
  'config',
  'url',
  'wsf',
  'wsh',
  'hta',
  'js',
  'vbs',
  'iss',
  'nsi',
  'nsh',
  'ahk',
  'au3',
  'sln',
  'csproj',
  'vbproj',
  'vcxproj',
  'xaml',
  'resx',
  'rc'
]
const CODE_EXTS = [
  'json',
  'html',
  'htm',
  'css',
  'scss',
  'less',
  'js',
  'jsx',
  'ts',
  'tsx',
  'py',
  'go',
  'rs',
  'java',
  'c',
  'h',
  'cpp',
  'hpp',
  'cs',
  'fs',
  'vb',
  'pas',
  'rb',
  'php',
  'pl',
  'kt',
  'swift',
  'sql',
  'sh',
  'bash',
  'ps1',
  'yaml',
  'yml',
  'toml',
  'xml',
  'svg',
  'lua',
  'r',
  'dart',
  'vue',
  'cshtml',
  'bat',
  'cmd',
  'vbs'
]

function unique(exts: string[]): string[] {
  return [...new Set(exts)]
}

export const OPEN_FILTERS: FileFilter[] = [
  { name: 'テキスト', extensions: unique(TEXT_EXTS) },
  { name: 'Windows', extensions: unique(WINDOWS_EXTS) },
  { name: 'コード', extensions: unique(CODE_EXTS) },
  { name: 'すべてのファイル', extensions: ['*'] }
]

export function languageFromFileName(fileName: string): string | null {
  const lower = fileName.toLowerCase()
  if (LANGUAGE_BY_FILENAME[lower]) return LANGUAGE_BY_FILENAME[lower]
  if (lower.startsWith('dockerfile')) return 'dockerfile'
  if (lower.startsWith('.') && LANGUAGE_BY_FILENAME[lower.slice(1)]) {
    return LANGUAGE_BY_FILENAME[lower.slice(1)]
  }
  const ext = lower.includes('.') ? lower.slice(lower.lastIndexOf('.') + 1) : ''
  if (ext && LANGUAGE_BY_EXT[ext]) return LANGUAGE_BY_EXT[ext]
  return null
}
